### ISSUE TITLE
include is deprecated

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/isam-ansible-collection#103]
As of Ansible 2.4 (or earlier?), it is stated that usage of "- include:" such as in the role first_steps is deprecated and should be replaced with "-include_tasks:" (which was made available starting in in 2.4).
Since the collection framework requires at least version Ansible 2.9 to work, I am assuming it is safe to update code to use include_tasks in the collection framework implementation of the first_steps role.
Will see to push a patch soon.

**Comment by tombosmansibm** [comment]
This has been resolved.
