### ISSUE TITLE
Conflicting tasks in roles/add_cluster_node/tasks/main.yml

### ISSUE THREAD

**Issue by Franclaf7** [IBM-Security/isam-ansible-collection#108]
There's a missing line to start the second task in roles/add_cluster_node/tasks/main.yml file. The first task "stat" is then in conflict with "ibm.isam.isam" because of this.

The playbook crashes with a **ERROR! conflicting action statements: stat, ibm.isam.isam**

**Comment by tombosmansibm** [comment]
Ansible-lint can now finish without crashing, this role is fixed as a side-effect
