### ISSUE TITLE
Exporting application logs role

### ISSUE THREAD

**Issue by cookieninja** [IBM-Security/isam-ansible-collection#128]
I cannot figure out how to use this role, the playbook provided in the collection does not work for me. I've seen there may be one or two parameters. My test playbook looks like this. What am I doing wrong? I've tried "file_path" and "filename" instead of path and file, as well as using the playbook in the collection "as is" without either of these parameters. Output is showing a long list of files in JSON format and other test playbooks work okay. Github is messing up formatting, so please assume I got this laid out right

 \# main task to export all application log files

 \- hosts: "isam_appliances"
   gather_facts: no
   roles:
     - role: ibm.isam.export_application_logs
       tags: export_application_logs
       path: "management_ui"
       name: "trace_21.03.17_10.25.52.0.log"

**Comment by tombosmansibm** [comment]
There's a parameter missing in the role - filename is missing on the get_file().  This is a bug in the role.
