### ISSUE TITLE
extract_certificates.yml file contains incorrect role

### ISSUE THREAD

**Issue by glinker** [IBM-Security/isam-ansible-collection#130]
In the isam-ansible-collection-master/playbooks/base/extract_certificates.yml file, there is a '/' in the role name causing the ansible-playbook command to fail with "no role found". 

- role: ibm.isam.base/extract_certificates 

should be: 
- role: ibm.isam.base.extract_certificates

**Comment by djorgen-ibm** [comment]
This has been fixed by pull request #132
