### ISSUE TITLE
'loop_control' value must be specified as a dictionary and cannot be a variable itself

### ISSUE THREAD

**Issue by glinker** [IBM-Security/isam-ansible-collection#131]
I'm attempting to run the extract_certificates playbook: 
ansible-playbook -i ./inventory/hosts /home/ansible-user/isam-ansible-collection-master/playbooks/base/extract_certificates.yml 

my host_vars/isva-1.yml file contains: 

[...]
extract_certificates:
        - kdb_id: "{{ pdsrv.kdb }}"
        cert_id: "{{ 'WebSEAL-Test-Only' }}"
        password: "{{ 'pdsrv' }}"
        filename: "{{ 'home/automation/inventory'}}/{{ 'webseal.crt' }}"

[...]

When running the playbook, I get the following error: 
ERROR! the `loop_control` value must be specified as a dictionary and cannot be a variable itself (though it can contain variables)

**Comment by djorgen-ibm** [comment]
This has been fixed in pull request #132.
