### ISSUE TITLE
Ansible role for STS chain has issues

### ISSUE THREAD

**Issue by csguin** [IBM-Security/isam-ansible-collection#146]
Hello,

When I use the STS chain ansible role to create the STS chain (not template) I see below error: **"msg": "Error> action does not have the right set of arguments or there is a code bug!**

Here is the YAML playbook.

- hosts: "{{ hosts | default('dev')}}"
  connection: local
  gather_facts: no  
  vars_prompt:
    - name: "username"
      prompt: "What is your username?"
      private: no
    - name: password
      prompt: "What is your password?"
  vars:
    lmi_port: 443
  roles:    
    - role: fed/configure_sts_chains
      tags: configure_sts_chains
      sts_chains:
       - name: aggregation-jwt2_temp
         chainId: uuidf1f61483-1f07-4d2a-a2ad-1b0a17b85f96
         description: "STS chain to issue JWT for aggregators"
         requestType: http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue
         sendValidationConfirmation: false
         validateRequests: false
         appliesTo: 
            address: aggregation-jwt2
         issuer: 
            address: amwebrte-sts-client 
         tokenType: urn:ietf:params:oauth:token-type:jwt
         signResponses: false
         properties:
           partner:
             - name: uuidd0f84f62-ddf4-4a2e-8f81-010128d72d91.ivcred.verify.signatures
               value:
                 - false
           self:
             - name: FIMConsole.EntGroup.Type
               value:
                 - OTHER
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.alg
               value:
                 - RS256
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.includeIat
               value:
                 - false
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.exp
               value:
                 - 0
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.cert
               value:
                 - taidpkey
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.jtiLength
               value:
                 - 0
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.db
               value:
                 - myidpkeys
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.nbfOffset
               value:
                 - -1
             - name: uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.reference.ids
               value:
                 - 530
             - name: uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.type
               value:
                 - JAVASCRIPT

I am pretty sure, the parameters are correct as the similar payload works for RESTAPI via postman. Just thinking if the ansible role for STS chain is tested for this usecase, if so, can someone share me a working YAML?.. Please suggest.

Thanks,
Chandra.

**Comment by djorgen-ibm** [comment]
Hi,

The role calls ibmsecurity.isam.fed.sts.module_chains.set which takes the following parameters:
        name, chainName, requestType, description=None, tokenType=None, xPath=None, signResponses=None,
        signatureKey=None, validateRequests=None, validationKey=None, sendValidationConfirmation=None, issuer=None,
        appliesTo=None, properties=None, new_name=None, ignore_password_for_idempotency=False, check_mode=False,
        force=False
You would need to modify the input to match those parameters.  For example, you can't pass in chainId.

**Comment by csguin** [comment]
> Hi,
> 
> The role calls ibmsecurity.isam.fed.sts.module_chains.set which takes the following parameters:
> name, chainName, requestType, description=None, tokenType=None, xPath=None, signResponses=None,
> signatureKey=None, validateRequests=None, validationKey=None, sendValidationConfirmation=None, issuer=None,
> appliesTo=None, properties=None, new_name=None, ignore_password_for_idempotency=False, check_mode=False,
> force=False
> You would need to modify the input to match those parameters. For example, you can't pass in chainId.

Thanks @djorgen-ibm .. I checked the code it doesnt expect a chainId. I rectified that.. Here is my playbook.. It passes with --check mode but fails when I remove --check flag. It expects a String whereas I am sending boolean. Can you please suggest what I am missing? Otherwise, if u have a workable yaml, can you please share one?

YAML
------------------
- hosts: "{{ hosts | default('dev')}}"
  connection: local
  gather_facts: no  
  vars_prompt:
    - name: "username"
      prompt: "What is your username?"
      private: no
    - name: password
      prompt: "What is your password?"
  vars:
    lmi_port: 443
    force: true
  roles:    
    - role: fed/configure_sts_chains
      tags: configure_sts_chains
      sts_chains:
       - name: aggregation-jwt2_temp
         chainName: IVC_to_JWT
         description: "STS chain to issue JWT for aggregators"
         requestType: http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue
         sendValidationConfirmation: false
         validateRequests: false
         appliesTo: 
            address: aggregation-jwt2
         issuer: 
            address: amwebrte-sts-client 
         tokenType: urn:ietf:params:oauth:token-type:jwt
         signResponses: false
         properties:
           partner:
             - name: uuidd0f84f62-ddf4-4a2e-8f81-010128d72d91.ivcred.verify.signatures
               value:
                 - false
           self:
             - name: FIMConsole.EntGroup.Type
               value:
                 - OTHER
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.alg
               value:
                 - RS256
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.includeIat
               value:
                 - false
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.exp
               value:
                 - 0
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.cert
               value:
                 - taidpkey
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.jtiLength
               value:
                 - 0
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.db
               value:
                 - myidpkeys
             - name: uuide8743fd4-f34e-4b21-8a46-954610c5d35b.nbfOffset
               value:
                 - -1
             - name: uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.reference.ids
               value:
                 - 530
             - name: uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.type
               value:
                 - JAVASCRIPT

Error Output
-------
failed: [crisamdev01a.us.aegon.com] (item={u'description': u'STS chain to issue JWT for aggregators', u'tokenType': u'urn:ietf:params:oauth:token-type:jwt', u'issuer': {u'address': u'amwebrte-sts-client'}, u'requestType': u'http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue', u'appliesTo': {u'address': u'aggregation-jwt2'}, u'signResponses': False, u'validateRequests': False, u'chainName': u'IVC_to_JWT', u'properties': {u'partner': [{u'name': u'uuidd0f84f62-ddf4-4a2e-8f81-010128d72d91.ivcred.verify.signatures', u'value': [False]}], u'self': [{u'name': u'FIMConsole.EntGroup.Type', u'value': [u'OTHER']}, {u'name': u'uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.alg', u'value': [u'RS256']}, {u'name': u'uuide8743fd4-f34e-4b21-8a46-954610c5d35b.includeIat', u'value': [False]}, {u'name': u'uuide8743fd4-f34e-4b21-8a46-954610c5d35b.exp', u'value': [0]}, {u'name': u'uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.cert', u'value': [u'taidpkey']}, {u'name': u'uuide8743fd4-f34e-4b21-8a46-954610c5d35b.jtiLength', u'value': [0]}, {u'name': u'uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.db', u'value': [u'myidpkeys']}, {u'name': u'uuide8743fd4-f34e-4b21-8a46-954610c5d35b.nbfOffset', u'value': [-1]}, {u'name': u'uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.reference.ids', u'value': [530]}, {u'name': u'uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.type', u'value': [u'JAVASCRIPT']}]}, u'sendValidationConfirmation': False, u'name': u'aggregation-jwt2_temp'}) => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "ansible_loop_var": "item", "changed": false, "item": {"appliesTo": {"address": "aggregation-jwt2"}, "chainName": "IVC_to_JWT", "description": "STS chain to issue JWT for aggregators", "issuer": {"address": "amwebrte-sts-client"}, "name": "aggregation-jwt2_temp", "properties": {"partner": [{"name": "uuidd0f84f62-ddf4-4a2e-8f81-010128d72d91.ivcred.verify.signatures", "value": [false]}], "self": [{"name": "FIMConsole.EntGroup.Type", "value": ["OTHER"]}, {"name": "uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.alg", "value": ["RS256"]}, {"name": "uuide8743fd4-f34e-4b21-8a46-954610c5d35b.includeIat", "value": [false]}, {"name": "uuide8743fd4-f34e-4b21-8a46-954610c5d35b.exp", "value": [0]}, {"name": "uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.cert", "value": ["taidpkey"]}, {"name": "uuide8743fd4-f34e-4b21-8a46-954610c5d35b.jtiLength", "value": [0]}, {"name": "uuide8743fd4-f34e-4b21-8a46-954610c5d35b.signing.db", "value": ["myidpkeys"]}, {"name": "uuide8743fd4-f34e-4b21-8a46-954610c5d35b.nbfOffset", "value": [-1]}, {"name": "uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.reference.ids", "value": [530]}, {"name": "uuid46e90685-e917-4edd-8d9c-62bf7533a101.map.rule.type", "value": ["JAVASCRIPT"]}]}, "requestType": "http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue", "sendValidationConfirmation": false, "signResponses": false, "tokenType": "urn:ietf:params:oauth:token-type:jwt", "validateRequests": false}, "log": "[2021-09-10 15:41:12,461] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving version ***\n[2021-09-10 15:41:12,470] [PID:27883 TID:140564332189504] [INFO] [urllib3.connectionpool] [_new_conn():735] Starting new HTTPS connection (1): crisamdev01a.us.aegon.com\n[2021-09-10 15:41:13,427] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Get Setup Complete Settings ***\n[2021-09-10 15:41:13,428] [PID:27883 TID:140564332189504] [INFO] [urllib3.connectionpool] [_new_conn():735] Starting new HTTPS connection (1): crisamdev01a.us.aegon.com\n[2021-09-10 15:41:14,370] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving activations ***\n[2021-09-10 15:41:14,370] [PID:27883 TID:140564332189504] [INFO] [urllib3.connectionpool] [_new_conn():735] Starting new HTTPS connection (1): crisamdev01a.us.aegon.com\n[2021-09-10 15:41:15,320] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieve a list of STS chains ***\n[2021-09-10 15:41:15,320] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_process_warnings():119] Modules satisfying requirement: [u'federation']\n[2021-09-10 15:41:15,322] [PID:27883 TID:140564332189504] [INFO] [urllib3.connectionpool] [_new_conn():735] Starting new HTTPS connection (1): crisamdev01a.us.aegon.com\n[2021-09-10 15:41:16,080] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.isam.fed.sts.module_chains] [set():70] STS Chain aggregation-jwt2_temp had no match, requesting to add new one.\n[2021-09-10 15:41:16,080] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieve a list of STS chain templates ***\n[2021-09-10 15:41:16,080] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_process_warnings():119] Modules satisfying requirement: [u'federation']\n[2021-09-10 15:41:16,081] [PID:27883 TID:140564332189504] [INFO] [urllib3.connectionpool] [_new_conn():735] Starting new HTTPS connection (1): crisamdev01a.us.aegon.com\n[2021-09-10 15:41:16,644] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.isam.fed.sts.templates] [search():30] Found STS Chain Template IVC_to_JWT id: uuidf1f61483-1f07-4d2a-a2ad-1b0a17b85f96\n[2021-09-10 15:41:16,644] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Create an STS chain ***\n[2021-09-10 15:41:16,644] [PID:27883 TID:140564332189504] [INFO] [ibmsecurity.appliance.ibmappliance] [_process_warnings():119] Modules satisfying requirement: [u'federation']\n[2021-09-10 15:41:16,646] [PID:27883 TID:140564332189504] [INFO] [urllib3.connectionpool] [_new_conn():735] Starting new HTTPS connection (1): crisamdev01a.us.aegon.com\n[2021-09-10 15:41:17,170] [PID:27883 TID:140564332189504] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():46]   Request failed: \n[2021-09-10 15:41:17,170] [PID:27883 TID:140564332189504] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():47]      status code: 500\n[2021-09-10 15:41:17,170] [PID:27883 TID:140564332189504] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():49]      text: {\"result\":\"java.lang.Boolean incompatible with java.lang.String\"}\n", "msg": "('HTTP Return code: 500', u'{\"result\":\"java.lang.Boolean incompatible with java.lang.String\"}')", "name": "ibmsecurity.isam.fed.sts.module_chains.set"}
