### ISSUE TITLE
"AssertionError: socket_path must be a value" using python 3.9.7/ansible 4.7.0 running ISAM playbook

### ISSUE THREAD

**Issue by leungk1234** [IBM-Security/isam-ansible-collection#147]
10.85.158.21> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.85.158.21> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.85.158.21> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494 `" && echo ansible-tmp-1634671937.5714831-5637-197440173555494="` echo /root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/ibm/isam/plugins/modules/isamadmin.py
<10.85.158.21> PUT /root/.ansible/tmp/ansible-local-5629rqyvc4rk/tmpe637qbon TO /root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py
<10.85.158.21> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/ /root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py && sleep 0'
<10.85.158.21> EXEC /bin/sh -c '/opt/bin/python3 /root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py && sleep 0'
<10.85.158.21> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py", line 100, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.isam.plugins.modules.isamadmin', init_globals=dict(_module_fqn='ansible_collections.ibm.isam.plugins.modules.isamadmin', _modlib_path=modlib_path),
  File "/opt/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py", line 114, in <module>
  File "/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py", line 92, in main
  File "/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/module_utils/isam.py", line 16, in __init__
  File "/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible/module_utils/connection.py", line 124, in __init__
AssertionError: socket_path must be a value
fatal: [10.85.158.21]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1634671937.5714831-5637-197440173555494/AnsiballZ_isamadmin.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ibm.isam.plugins.modules.isamadmin', init_globals=dict(_module_fqn='ansible_collections.ibm.isam.plugins.modules.isamadmin', _modlib_path=modlib_path),\n  File \"/opt/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/opt/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/opt/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py\", line 114, in <module>\n  File \"/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py\", line 92, in main\n  File \"/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/module_utils/isam.py\", line 16, in __init__\n  File \"/tmp/ansible_ibm.isam.isamadmin_payload_2wi20nu3/ansible_ibm.isam.isamadmin_payload.zip/ansible/module_utils/connection.py\", line 124, in __init__\nAssertionError: socket_path must be a value\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Is it missing some configuration properties that causes the isam.py behaves this way?

**Comment by leungk1234** [comment]
so what is the variable name for sec_master and sec_master password for the new collection of roles?

**Comment by leungk1234** [comment]
Is it still the same as this one:
sec_master_id: "sec_master"
sec_master_pwd: "{{vault_sec_master_pwd}}"

**Comment by djorgen-ibm** [comment]
are you running the playbook using isam-ansible-collection?  the isam-ansible-collection is not just a collection of playbooks and roles but it has connection plugins so when you run the playbook, your environment has to be setup to use the isam-ansible-collection.

**Comment by leungk1234** [comment]
yes that is what I am using. So here is the end product for the invemtories that works for isam, pdadmin and also compare:
hosts:
[isam_sandbox]
vap0xxx.allstate.com

[isam_sandbox:vars]
ansible_connection="ibm.isam.isam"
ansible_isam_port="443"
ansible_python_interpreter="/opt/bin/python3"
master_lmi_port="443"

isam_sandbox file:
---
ansible_isam_username: "admin@local"
ansible_isam_password: "xxxxx"
sec_master_id: "sec_master"
sec_master_pwd: "xxxx"
master_username: "admin@local"
master_password: "xxxxx"


I do not know which sec)master line that works in pdadmin.yml and also compare.yml but it works with both in there.

**Comment by leungk1234** [comment]
just looking at the roles for access policy. I do not see any roles for list or delete access policy in the IBM ansible roles. The only roles there is to set the access policy.
