### ISSUE TITLE
ibm.isam.isam connection no longer works

### ISSUE THREAD

**Issue by tombosmansibm** [IBM-Security/isam-ansible-collection#161]
In recent versions of Ansible (problem started for me on ansible core 2.13.4, but may exist in earlier versions), the ibm.isam.isam connection no longer works.

```
TASK [ibm.isam.configure_reverseproxy_instances : Configure reverse proxy instances] *********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Connection' object has no attribute 'nonetype'
fatal: [isam]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by rohithhthakur** [comment]
Hi @tombosmansibm 
I am facing same issue 
Workflow seems to work fine before the upgrade, We have upgraded the Ansible tower to AAP 2.1 and then trying custom execution environemnt is having connection issue

{"msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Connection' object has no attribute 'nonetype'

**Comment by rohithhthakur** [comment]
Hi @tombosmansibm 

Thank you for your help
I have replaced the isam.py file with my current isam.py and I am still facing same issue. Any suggestions please?
I am using a custom execution environment in Ansible automation platform

- **Collection and ansible versions used**
  collections:
    - awx.awx
    - redhat_cop.controller_configuration
    - ibm.isam
    - community.general

**Ansible version used in podman container spinned up from custom execution environment image:**

ansible [core 2.12.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 [20210514](https://access.redhat.com/support/cases/#/case/20210514) (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
