### ISSUE TITLE
APAR IJ45283 changing junction create REST API command, case_sensitive_url parameter

### ISSUE THREAD

**Issue by HandCarvedWoodenSpoon** [IBM-Security/isam-ansible-collection#169]
Be aware, there is an APAR for ISVA v10.0.5. The REST API uses “case_sensitive” while the junction output uses “case insensitive”. The resulting junction is created successfully but the pdadmin server task show output shows the opposite behavior.

The APAR fix will change the REST API command to create a junction. The APAR fix changes the parameter "case_sensitive_url" to become "case_insensitive_url". The APAR fix matches the text in the LMI. The APAR fix will be included in v10.0.6.

"case_sensitive_url":"no"   <-- old method
"case_insensitive_url":"yes"   <-- v10.0.6 method

APAR Error description:
In the following text, pay careful attention to the use of sensitive and insensitive.

When you create a junction with a REST API command and specify JSON with "case_sensitive_url":"no", the resulting junction show output will show "Case insensitive URLs: no". The no value is consistent, but sensitive/insensitive words have been switched. Unexpectedly, the opposite behavior for the setting is now configured.

**Comment by tombosmansibm** [comment]
I'm picking this up in the ibmsecurity code (https://github.com/IBM-Security/ibmsecurity/issues/386)

**Comment by tombosmansibm** [comment]
Fixed in https://pypi.org/project/ibmsecurity/2023.6.30.0/
