### ISSUE TITLE
The "ibm.isam.isam" connection plugin has an improperly configured remote target value, forcing "inventory_hostname" templated value instead of the string. 

### ISSUE THREAD

**Issue by tombosmansibm** [IBM-Security/isam-ansible-collection#172]
Implement this fix:
https://github.com/ansible/ansible/pull/77844/commits/a50dcefc2c6417fd956a8d8dec32f763068a011b

**Comment by ldesrosi** [comment]
Hi @tombosmansibm.  Do you know if there are plans to update Ansible Galaxy with the latest of the collection?
  
I've noticed that the version that is on Ansible Galaxy is missing the `inventory_hostname` in the `plugins\connection\isam.py` so even with the fix you listed above we still get the error when installing the collection using ansible-galaxy.

Thank you.

**Comment by tombosmansibm** [comment]
Hi, yes, I hope to release a new version this week.
