### ISSUE TITLE
configure_reverseproxy_instances.yml failed with Failed to template loop_control.label

### ISSUE THREAD

**Issue by mohinz-ibm** [IBM-Security/isam-ansible-collection#176]
/root/.ansible/collections/ansible_collections/ibm/isam/roles/web/configure_reverseproxy_instances/tasks/main.yml Failed with
"msg": "Failed to template loop_control.label: the inline if-expression on line 1 evaluated to false and no else section was defined."
when inventory use the following template
- method: set
  stanza_id: rsp-header-names
  entries:
  - [strict-transport-security, max-age=31536000; includeSubDomains]
  - [clear-site-data, storage]
  - [cache-control, max-age=0; no-cache; no-store; must-revalidate]

As a temporary work around, I replaced
label: "{'method': {{ item.1.method }}, inst_name: {{ item.0.inst_name }}, stanza_id: {{ item.1.stanza_id }}{{ (', ' + \"'entries'\" + ': ' + (item.1.entries | join(''))) if item.1.entries is defined }}{{ (', ' + \"'entry_id'\" + ': ' + item.1.entry_id) if item.1.entry_id is defined }}{{ (', ' + \"'value_id'\" + ': ' + item.1.value_id) if item.1.value_id is defined }}}"

with
label: "{'method': {{ item.1.method }}, inst_name: {{ item.0.inst_name }}, stanza_id: {{ item.1.stanza_id }}{{ (', ' + \"'entries'\" + ': ' + (item.1.entries | join(''))) if item.1.entries is defined }}}"

**Comment by tombosmansibm** [comment]
I've got a fix for that in this pull request https://github.com/IBM-Security/isam-ansible-collection/pull/177

**Comment by tombosmansibm** [comment]
fixed in version 1.0.29
