### ISSUE TITLE
the instances varialbe not set correctly from _instances in role web/config_reverseproxy_redis/tasks/main.yml

### ISSUE THREAD

**Issue by bjsong19** [IBM-Security/isam-ansible-collection#185]
Hello,
When I configure Redis with role web/config_reverseproxy_redis, I noticed following task is not executed because passed in instance variable is not the content from _instances although _instances itself is correct:

 - name: Enable/disable Redis enabled distributed session
  vars:
    instances: "{{ _instances }}"
  include_role:
    name: web/configure_reverseproxy_instances
  when:
    - _instances is defined
  
This is because instances variable is already used in previous tasks and it is not updated in the above task due to variable scope issue I think.

Can you review and validate to ensure both **web/config_reverseproxy_redis** and **web/configure_reverseproxy_instances** works correctly together?

Thanks, could you please have fix to be available asap?

**Comment by tombosmansibm** [comment]
I'll take a look.  Thanks for opening an issue
