### ISSUE TITLE
Use of base.install_fixpacks role fails every time.

### ISSUE THREAD

**Issue by iwamitsu** [IBM-Security/isam-ansible-collection#189]
When using the base.install_fixpacks role to apply FixPack, the application is successful, but the execution fails.

`TASK [ibm.isam.base.install_fixpacks : Install single fixpack file [fix_pack_file]] **********************************************
fatal: [isva10]: FAILED! => {"ansible_facts": {"activations": ["wga"], "firmware_build": "20231130-1943", "firmware_label": "isva_10.0.7.0_20231130-1943_", "model": "Appliance", "product_description": "IBM Security Verify Access", "product_name": "isva", "version": "10.0.7.0"}, "changed": true, "cmd": "ibmsecurity.isam.base.fixpack.install(isamAppliance=self.isam_server, force=False, file=\"/ibm/isvaansible/./files/10.0.7.0_IF1.fixpack\")", "data": "", "delta": "0:00:21.625787", "end": "2024-04-24 11:23:27.318438", "failed_when_result": true, "rc": 0, "start": "2024-04-24 11:23:05.692651", "status_code": 0, "stdout": "", "stdout_lines": [""]}`

After checking the base.install_fixpacks role task, I found a problem with the way the return code is checked.

failed_when: result.rc not in ["0"]
-> failed_when: result.rc not in [0]

Could you please fix this?

**Comment by tombosmansibm** [comment]
fixed in #191
