### ISSUE TITLE
Role to configure configure the Authentication and Context Based Access service ( authsvc_config)

### ISSUE THREAD

**Issue by ramraj241** [IBM-Security/isam-ansible-collection#77]
Hello,

Is there any role available to configure reverse proxy instance to configure the Authentication and Context Based Access service ? Upon observation, behind the hood it looks like this is the api call being leveraged 

https://appliancehost/wga/reverseproxy/rp-instance/authsvc_config

If there is no such role available, which particular python code has function to get this done via custom role?

**Comment by ram-ibm** [comment]
https://github.com/IBM-Security/isam-ansible-collection/tree/master/roles/config_reverseproxy_aac
